services:
  - type: web
    name: college-chatbot
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn college_chatbot.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: college-chatbot.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: college-chatbot-db
          property: connectionString
    autoDeploy: true

databases:
  - name: college-chatbot-db
    plan: free
